### ISSUE TITLE
completed_shipment_day_shown doesn't work for returned packages

### ISSUE THREAD

**Issue by Dis90** [jesmak/posti_tracking#3]
Hi,

Setting completed_shipment_day_shown is not respected if package is returned to sender (or this probably applies to all self-sent packages).

```
packages: 
- origin: XXXX XXXXX
  origin_city: XXXXXXX
  destination: XXXXXX Ky
  destination_city: HELSINKI
  shipment_number: JJFIXXXXXX
  shipment_date: '2024-08-09T14:18:25Z'
  status: 6
  raw_status: RETURNED_TO_SENDER
  latest_event: Lähetys on toimitettu perille.
  latest_event_city: null
  latest_event_country: FI
  latest_event_date: '2024-08-13T08:40:05Z'
  source: Posti

```
